[Final] ПР1 готова для ревью.
kspshnik/s-chistogo-lista pull request #3
Opened 2024-08-17 15:21 UTC by kspshnik

Реализованы все секции из брифа, требования чек-листа выполнены

2024-08-17 17:27 UTC, seginel requested changes
Здравствуйте, У вас получилась хорошая работа, но в ней есть замечания - здесь понадобятся доработки.

### Что понравилось

* Аккуратное форматирование кода
* Используются сематические теги
* Размечена вся структура
* Страница визуально похожа на макет
* Страница валидна
* Правильно оформлен head

### Что нужно поправить

* Все комментарии "Надо исправить" в коде.
* Страница визуально должна соответствовать макету. Отличие не должно превышать 10px по вертикали и 5px по горизонтали. Для доводки вёрстки рекомендую использовать плагин [Pixel Perfect](https://www.welldonecode.com/perfectpixel/){target="_blank"}
    * https://disk.yandex.ru/i/K0HbYdrqSl16cA
    * https://disk.yandex.ru/i/yO39tlfOojf6ag 
    * Проверьте правильность заголовка в последней карточке: https://disk.yandex.ru/i/U6rzz1f8rpO2mw
* После внесения правок проверьте код в валидаторе https://validator.w3.org/nu/#textarea, там не должно быть критических ошибок типа ERROR. При наличии ошибок - их нужно проанализировать и исправить (если эта ошибка не противоречит другим пунктам в чеклиста к проекту).
* Стоит напомнить, что все замечания не придумываются ревьюером на ходу. Они формируются на основе чеклиста и брифа к заданию. Если соблюсти все требования чеклиста и рекомендаций в брифе, то работа будет сразу же принята. Поэтому перед отправкой на следующую итерацию рекомендую самостоятельно пройтись по брифу и чеклисту и при необходимости поправить все проблемные места. Это позволит быстрее получить зачёт по работе.

### Что можно лучше

* Все комментарии "Можно лучше" в коде.

Комментарии "можно лучше" носят рекомендательный характер, их выполнение остается на Ваше усмотрение. Комментарии "надо исправить" являются обязательными, при выполнении всех "надо исправить" работа будет зачтена. Удачи

2024-08-17 17:27 UTC, seginel commented on index.html
> +  <link rel="stylesheet" href="./styles/style.css">
Отлично. Файлы подключены в правильном порядке: сначала шрифты, потом собственные стили

2024-08-17 17:27 UTC, seginel commented on styles/style.css
> +  min-height: 100px;
Надо исправить.
В этих блоках есть текст, а у текста не должно быть высоты. Высота контейнера с текстом должна зависеть от количества самого текста - если текста нет, то высота = 0, если текст есть, то высота определяется числом занимаемых строк и значением `line-height`
Данную строку нужно удалить

2024-08-17 17:27 UTC, seginel commented on styles/style.css
> +  max-height: 40px;
Нужно убрать ограничение высоты, высота должна зависеть от количества контента внутри контейнера. В этом блоке есть текст, который может быть короче или длиннее. Высоты здесь быть не должно

2024-08-17 17:27 UTC, seginel commented on styles/style.css
> +  font-family: 'EB Garamond';
Надо исправить
В свойстве `font-family` кроме основного шрифта так же должен быть указан альтернативный шрифт или тип засечек (или всё вместе). Это делается для случая, если по каким-то причинами основной шрифт не загрузится, то будет загружен альтернативный или другой шрифт с подходящим типом засечек - таким образом внешний вид страницы не будет изменен очень сильно. Порядок написания шрифтов: `Основной шрифт, Тип засечек` или `Основной шрифт, Веб-безопасный альтернативный шрифт, Тип засечек`. Список безопасных шрифтов: https://www.cssfontstack.com/.

Правки необходимо внести во все места, где встречается такой же недочёт.

2024-08-17 17:27 UTC, seginel commented on styles/style.css
> +  border-bottom: solid 1px #FEE42A;
Можно лучше:
Этот бордер я бы порекомендовал реализовать у футера.

Визуально бордер отделяет основной контент от футера. Но если футер удалить, то в этом бордере не будет необходимости. Поэтому по смыслу бордер больше относится к футеру - тогда бордер тоже удалится при удалении футера.

2024-08-17 18:07 UTC, kspshnik commented on styles/style.css
> +  min-height: 100px;
Забыл от отладки :(
Удалено.

2024-08-17 18:09 UTC, kspshnik commented on styles/style.css
> +  max-height: 40px;
Аналогично, что-то подбирал и забыл почистить :(

Убрано.

2024-08-17 18:25 UTC, kspshnik commented on styles/style.css
> +  font-family: 'EB Garamond';
Поправил в трёх местах, и улучшил в четвёртом :)

2024-08-17 18:44 UTC, kspshnik commented on styles/style.css
> +  border-bottom: solid 1px #FEE42A;
Перенес.

2024-08-18 14:08 UTC, seginel approved these changes
Спасибо за правки. Вы внесли исправления по всем замечаниям и хочу поздравить - Вы отлично справились с выполнением проектной работы. По странице у меня больше нет замечаний: страница соответствует макету и требованиям чеклиста.
Работу принимаю. Удачи в дальнейшем обучении.

2024-08-18 14:46 UTC, merged